#####
#  GitHub Pages / Jekyll settings / config

headers:
  title:     SENI POP
  subtitle:  1950-an hingga 1970-an
  author:    Aliran dan gaya
  generator: GitHub Pages w/ Jekyll
  theme:     black


collections:
  slides:
    output: false


exclude:
- README.md
- BUILD.md
- CHANGELOG.md
- LICENSE.reveal.js.txt
- reveal.js.txt
- sample.md
